// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AddressEntUsers string
	Addresses       string
	Categories      string
	Countries       string
	EntAddresses    string
	EntCountries    string
	EntUsers        string
	Links           string
	LinksCategories string
	UserAddresses   string
	Users           string
}{
	AddressEntUsers: "address_entUsers",
	Addresses:       "addresses",
	Categories:      "categories",
	Countries:       "countries",
	EntAddresses:    "entAddresses",
	EntCountries:    "entCountries",
	EntUsers:        "entUsers",
	Links:           "links",
	LinksCategories: "links_categories",
	UserAddresses:   "user_addresses",
	Users:           "users",
}
