// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Addresses     string
	Countries     string
	UserAddresses string
	Users         string
}{
	Addresses:     "addresses",
	Countries:     "countries",
	UserAddresses: "user_addresses",
	Users:         "users",
}
