// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EntCountry is an object representing the database table.
type EntCountry struct {
	ID   int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Code string `boil:"code" json:"code" toml:"code" yaml:"code"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *entCountryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L entCountryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EntCountryColumns = struct {
	ID   string
	Code string
	Name string
}{
	ID:   "id",
	Code: "code",
	Name: "name",
}

var EntCountryTableColumns = struct {
	ID   string
	Code string
	Name string
}{
	ID:   "entCountries.id",
	Code: "entCountries.code",
	Name: "entCountries.name",
}

// Generated where

var EntCountryWhere = struct {
	ID   whereHelperint64
	Code whereHelperstring
	Name whereHelperstring
}{
	ID:   whereHelperint64{field: "\"entCountries\".\"id\""},
	Code: whereHelperstring{field: "\"entCountries\".\"code\""},
	Name: whereHelperstring{field: "\"entCountries\".\"name\""},
}

// EntCountryRels is where relationship names are stored.
var EntCountryRels = struct {
	CountryEntAddressEntAddresses string
}{
	CountryEntAddressEntAddresses: "CountryEntAddressEntAddresses",
}

// entCountryR is where relationships are stored.
type entCountryR struct {
	CountryEntAddressEntAddresses EntAddressSlice `boil:"CountryEntAddressEntAddresses" json:"CountryEntAddressEntAddresses" toml:"CountryEntAddressEntAddresses" yaml:"CountryEntAddressEntAddresses"`
}

// NewStruct creates a new relationship struct
func (*entCountryR) NewStruct() *entCountryR {
	return &entCountryR{}
}

// entCountryL is where Load methods for each relationship are stored.
type entCountryL struct{}

var (
	entCountryAllColumns            = []string{"id", "code", "name"}
	entCountryColumnsWithoutDefault = []string{"code", "name"}
	entCountryColumnsWithDefault    = []string{"id"}
	entCountryPrimaryKeyColumns     = []string{"id"}
)

type (
	// EntCountrySlice is an alias for a slice of pointers to EntCountry.
	// This should almost always be used instead of []EntCountry.
	EntCountrySlice []*EntCountry
	// EntCountryHook is the signature for custom EntCountry hook methods
	EntCountryHook func(context.Context, boil.ContextExecutor, *EntCountry) error

	entCountryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	entCountryType                 = reflect.TypeOf(&EntCountry{})
	entCountryMapping              = queries.MakeStructMapping(entCountryType)
	entCountryPrimaryKeyMapping, _ = queries.BindMapping(entCountryType, entCountryMapping, entCountryPrimaryKeyColumns)
	entCountryInsertCacheMut       sync.RWMutex
	entCountryInsertCache          = make(map[string]insertCache)
	entCountryUpdateCacheMut       sync.RWMutex
	entCountryUpdateCache          = make(map[string]updateCache)
	entCountryUpsertCacheMut       sync.RWMutex
	entCountryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var entCountryBeforeInsertHooks []EntCountryHook
var entCountryBeforeUpdateHooks []EntCountryHook
var entCountryBeforeDeleteHooks []EntCountryHook
var entCountryBeforeUpsertHooks []EntCountryHook

var entCountryAfterInsertHooks []EntCountryHook
var entCountryAfterSelectHooks []EntCountryHook
var entCountryAfterUpdateHooks []EntCountryHook
var entCountryAfterDeleteHooks []EntCountryHook
var entCountryAfterUpsertHooks []EntCountryHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EntCountry) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EntCountry) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EntCountry) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EntCountry) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EntCountry) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EntCountry) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EntCountry) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EntCountry) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EntCountry) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range entCountryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEntCountryHook registers your hook function for all future operations.
func AddEntCountryHook(hookPoint boil.HookPoint, entCountryHook EntCountryHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		entCountryBeforeInsertHooks = append(entCountryBeforeInsertHooks, entCountryHook)
	case boil.BeforeUpdateHook:
		entCountryBeforeUpdateHooks = append(entCountryBeforeUpdateHooks, entCountryHook)
	case boil.BeforeDeleteHook:
		entCountryBeforeDeleteHooks = append(entCountryBeforeDeleteHooks, entCountryHook)
	case boil.BeforeUpsertHook:
		entCountryBeforeUpsertHooks = append(entCountryBeforeUpsertHooks, entCountryHook)
	case boil.AfterInsertHook:
		entCountryAfterInsertHooks = append(entCountryAfterInsertHooks, entCountryHook)
	case boil.AfterSelectHook:
		entCountryAfterSelectHooks = append(entCountryAfterSelectHooks, entCountryHook)
	case boil.AfterUpdateHook:
		entCountryAfterUpdateHooks = append(entCountryAfterUpdateHooks, entCountryHook)
	case boil.AfterDeleteHook:
		entCountryAfterDeleteHooks = append(entCountryAfterDeleteHooks, entCountryHook)
	case boil.AfterUpsertHook:
		entCountryAfterUpsertHooks = append(entCountryAfterUpsertHooks, entCountryHook)
	}
}

// One returns a single entCountry record from the query.
func (q entCountryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EntCountry, error) {
	o := &EntCountry{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for entCountries")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EntCountry records from the query.
func (q entCountryQuery) All(ctx context.Context, exec boil.ContextExecutor) (EntCountrySlice, error) {
	var o []*EntCountry

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EntCountry slice")
	}

	if len(entCountryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EntCountry records in the query.
func (q entCountryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count entCountries rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q entCountryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if entCountries exists")
	}

	return count > 0, nil
}

// CountryEntAddressEntAddresses retrieves all the entAddress's EntAddresses with an executor via country_ent_addresses column.
func (o *EntCountry) CountryEntAddressEntAddresses(mods ...qm.QueryMod) entAddressQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"entAddresses\".\"country_ent_addresses\"=?", o.ID),
	)

	query := EntAddresses(queryMods...)
	queries.SetFrom(query.Query, "\"entAddresses\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"entAddresses\".*"})
	}

	return query
}

// LoadCountryEntAddressEntAddresses allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (entCountryL) LoadCountryEntAddressEntAddresses(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEntCountry interface{}, mods queries.Applicator) error {
	var slice []*EntCountry
	var object *EntCountry

	if singular {
		object = maybeEntCountry.(*EntCountry)
	} else {
		slice = *maybeEntCountry.(*[]*EntCountry)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &entCountryR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &entCountryR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`entAddresses`),
		qm.WhereIn(`entAddresses.country_ent_addresses in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load entAddresses")
	}

	var resultSlice []*EntAddress
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice entAddresses")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on entAddresses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for entAddresses")
	}

	if len(entAddressAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.CountryEntAddressEntAddresses = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &entAddressR{}
			}
			foreign.R.CountryEntAddress = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.CountryEntAddresses) {
				local.R.CountryEntAddressEntAddresses = append(local.R.CountryEntAddressEntAddresses, foreign)
				if foreign.R == nil {
					foreign.R = &entAddressR{}
				}
				foreign.R.CountryEntAddress = local
				break
			}
		}
	}

	return nil
}

// AddCountryEntAddressEntAddresses adds the given related objects to the existing relationships
// of the entCountry, optionally inserting them as new records.
// Appends related to o.R.CountryEntAddressEntAddresses.
// Sets related.R.CountryEntAddress appropriately.
func (o *EntCountry) AddCountryEntAddressEntAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*EntAddress) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.CountryEntAddresses, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"entAddresses\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"country_ent_addresses"}),
				strmangle.WhereClause("\"", "\"", 2, entAddressPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.CountryEntAddresses, o.ID)
		}
	}

	if o.R == nil {
		o.R = &entCountryR{
			CountryEntAddressEntAddresses: related,
		}
	} else {
		o.R.CountryEntAddressEntAddresses = append(o.R.CountryEntAddressEntAddresses, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &entAddressR{
				CountryEntAddress: o,
			}
		} else {
			rel.R.CountryEntAddress = o
		}
	}
	return nil
}

// SetCountryEntAddressEntAddresses removes all previously related items of the
// entCountry replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.CountryEntAddress's CountryEntAddressEntAddresses accordingly.
// Replaces o.R.CountryEntAddressEntAddresses with related.
// Sets related.R.CountryEntAddress's CountryEntAddressEntAddresses accordingly.
func (o *EntCountry) SetCountryEntAddressEntAddresses(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*EntAddress) error {
	query := "update \"entAddresses\" set \"country_ent_addresses\" = null where \"country_ent_addresses\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.CountryEntAddressEntAddresses {
			queries.SetScanner(&rel.CountryEntAddresses, nil)
			if rel.R == nil {
				continue
			}

			rel.R.CountryEntAddress = nil
		}

		o.R.CountryEntAddressEntAddresses = nil
	}
	return o.AddCountryEntAddressEntAddresses(ctx, exec, insert, related...)
}

// RemoveCountryEntAddressEntAddresses relationships from objects passed in.
// Removes related items from R.CountryEntAddressEntAddresses (uses pointer comparison, removal does not keep order)
// Sets related.R.CountryEntAddress.
func (o *EntCountry) RemoveCountryEntAddressEntAddresses(ctx context.Context, exec boil.ContextExecutor, related ...*EntAddress) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.CountryEntAddresses, nil)
		if rel.R != nil {
			rel.R.CountryEntAddress = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("country_ent_addresses")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.CountryEntAddressEntAddresses {
			if rel != ri {
				continue
			}

			ln := len(o.R.CountryEntAddressEntAddresses)
			if ln > 1 && i < ln-1 {
				o.R.CountryEntAddressEntAddresses[i] = o.R.CountryEntAddressEntAddresses[ln-1]
			}
			o.R.CountryEntAddressEntAddresses = o.R.CountryEntAddressEntAddresses[:ln-1]
			break
		}
	}

	return nil
}

// EntCountries retrieves all the records using an executor.
func EntCountries(mods ...qm.QueryMod) entCountryQuery {
	mods = append(mods, qm.From("\"entCountries\""))
	return entCountryQuery{NewQuery(mods...)}
}

// FindEntCountry retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEntCountry(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*EntCountry, error) {
	entCountryObj := &EntCountry{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"entCountries\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, entCountryObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from entCountries")
	}

	if err = entCountryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return entCountryObj, err
	}

	return entCountryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EntCountry) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no entCountries provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(entCountryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	entCountryInsertCacheMut.RLock()
	cache, cached := entCountryInsertCache[key]
	entCountryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			entCountryAllColumns,
			entCountryColumnsWithDefault,
			entCountryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(entCountryType, entCountryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(entCountryType, entCountryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"entCountries\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"entCountries\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into entCountries")
	}

	if !cached {
		entCountryInsertCacheMut.Lock()
		entCountryInsertCache[key] = cache
		entCountryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EntCountry.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EntCountry) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	entCountryUpdateCacheMut.RLock()
	cache, cached := entCountryUpdateCache[key]
	entCountryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			entCountryAllColumns,
			entCountryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update entCountries, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"entCountries\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, entCountryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(entCountryType, entCountryMapping, append(wl, entCountryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update entCountries row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for entCountries")
	}

	if !cached {
		entCountryUpdateCacheMut.Lock()
		entCountryUpdateCache[key] = cache
		entCountryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q entCountryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for entCountries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for entCountries")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EntCountrySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), entCountryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"entCountries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, entCountryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in entCountry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all entCountry")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EntCountry) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no entCountries provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(entCountryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	entCountryUpsertCacheMut.RLock()
	cache, cached := entCountryUpsertCache[key]
	entCountryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			entCountryAllColumns,
			entCountryColumnsWithDefault,
			entCountryColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			entCountryAllColumns,
			entCountryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert entCountries, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(entCountryPrimaryKeyColumns))
			copy(conflict, entCountryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"entCountries\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(entCountryType, entCountryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(entCountryType, entCountryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert entCountries")
	}

	if !cached {
		entCountryUpsertCacheMut.Lock()
		entCountryUpsertCache[key] = cache
		entCountryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EntCountry record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EntCountry) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EntCountry provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), entCountryPrimaryKeyMapping)
	sql := "DELETE FROM \"entCountries\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from entCountries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for entCountries")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q entCountryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no entCountryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from entCountries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for entCountries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EntCountrySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(entCountryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), entCountryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"entCountries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, entCountryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from entCountry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for entCountries")
	}

	if len(entCountryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EntCountry) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEntCountry(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EntCountrySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EntCountrySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), entCountryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"entCountries\".* FROM \"entCountries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, entCountryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EntCountrySlice")
	}

	*o = slice

	return nil
}

// EntCountryExists checks if the EntCountry row exists.
func EntCountryExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"entCountries\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if entCountries exists")
	}

	return exists, nil
}
