// Code generated by sqlc. DO NOT EDIT.

package mariadb

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"time"
)

type UsersFavouriteColour string

const (
	UsersFavouriteColourRed   UsersFavouriteColour = "red"
	UsersFavouriteColourGreen UsersFavouriteColour = "green"
	UsersFavouriteColourBlue  UsersFavouriteColour = "blue"
)

func (e *UsersFavouriteColour) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersFavouriteColour(s)
	case string:
		*e = UsersFavouriteColour(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersFavouriteColour: %T", src)
	}
	return nil
}

type Address struct {
	ID        int64
	Line1     string
	Line2     sql.NullString
	Postcode  sql.NullInt32
	City      sql.NullString
	State     sql.NullString
	CountryID sql.NullInt64
}

type Country struct {
	ID   int64
	Code string
	Name string
}

type CountryAddress struct {
	ID           int64
	Code         string
	Name         string
	JsonArrayagg json.RawMessage
}

type User struct {
	ID              int64
	FirstName       string
	MiddleName      sql.NullString
	LastName        string
	Email           string
	Password        string
	FavouriteColour UsersFavouriteColour
	UpdatedAt       time.Time
}

type UserAddress struct {
	UserID    sql.NullInt64
	AddressID sql.NullInt64
}
