// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
)

type Address struct {
	ID        int64
	Line1     string
	Line2     sql.NullString
	Postcode  sql.NullInt32
	City      sql.NullString
	State     sql.NullString
	CountryID sql.NullInt64
}

type Country struct {
	ID   int64
	Code string
	Name string
}

type User struct {
	ID         int64
	FirstName  string
	MiddleName sql.NullString
	LastName   string
	Email      string
	Password   string
}

type UserAddress struct {
	UserID    sql.NullInt64
	AddressID sql.NullInt64
}
