version: '3.7'

services:

  postgres:
    image: "postgres:15"
    restart: unless-stopped
    container_name: "postgres15"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_test
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: pg_isready -U postgres
    volumes:
      - postgres15db:/var/lib/postgresql/data
      - ./database/01-postgres-schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres15db:
