output   = "db/sqlboiler/models"
wipe     = true
no-tests = true

[psql]
dbname = "db_test"
host   = "localhost"
port   = 5432
user   = "user"
pass   = "password"
sslmode = "disable"
schema = "public"
blacklist = ["migrations", "schema_migrations", "goose_db_version"]
