// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type Address struct {
	ID        int64
	Line1     string
	Line2     sql.NullString
	Postcode  sql.NullInt32
	City      sql.NullString
	State     sql.NullString
	CountryID sql.NullInt64
}

type Country struct {
	ID   int64
	Code string
	Name string
}

type CountryAddress struct {
	ID      int64
	Code    string
	Name    string
	Address json.RawMessage
}

type User struct {
	ID         int64
	FirstName  string
	MiddleName sql.NullString
	LastName   string
	Email      string
	Password   string
}

type UserAddress struct {
	UserID    int64
	AddressID int64
}
