// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"encoding/json"
	"fmt"
)

type ValidColours string

const (
	ValidColoursRed   ValidColours = "red"
	ValidColoursGreen ValidColours = "green"
	ValidColoursBlue  ValidColours = "blue"
)

func (e *ValidColours) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ValidColours(s)
	case string:
		*e = ValidColours(s)
	default:
		return fmt.Errorf("unsupported scan type for ValidColours: %T", src)
	}
	return nil
}

type Address struct {
	ID        int64
	Line1     string
	Line2     sql.NullString
	Postcode  sql.NullInt32
	City      sql.NullString
	State     sql.NullString
	CountryID sql.NullInt64
}

type Country struct {
	ID   int64
	Code string
	Name string
}

type CountryAddress struct {
	ID      int64
	Code    string
	Name    string
	Address json.RawMessage
}

type User struct {
	ID              int64
	FirstName       string
	MiddleName      sql.NullString
	LastName        string
	Email           string
	Password        string
	FavouriteColour ValidColours
}

type UserAddress struct {
	UserID    int64
	AddressID int64
}
